[[./resources/images/logo-long.svg]]

** Brand and Trademark Usage Guidelines

*** Trademark Guidelines

Any use of the GoForge Trademarks other than those permitted in these guidelines must be approved in advance.

In general, we want the word mark "GoForge" and the GoForge Slogan, "Crafting Code, Building Success" when associated therewith, to be used freely to refer to the GoForge programming language and its purpose.

We do not want the word mark "GoForge" to be used:

- to refer to any other command line tool.
- in a way that is misleading or may imply association of unrelated projects, companies, software, documentation, or other resources with the GoForge project.
- in ways that confuse the community as to whether the GoForge command line tool is open source and free to use.

These guidelines exist to ensure that the GoForge command line tool can continue to share its releases under open source licenses while making sure that the GoForge Trademarks are protected as meaningful source identifiers in a way that's consistent with trademark law.

*** License

The GoForge command line tool is licensed under the [[https://www.eclipse.org/legal/epl-2.0/][Eclipse Public License - v 2.0]]. Any use, reproduction or distribution of the program constitutes recipient's acceptance of said license.

*** Nominative Fair Use

GoForge is neither affiliated with, nor endorsed by the Go programming language community or Google.

*** No Implication of Official Status

Use of the name "GoForge" does not imply official status or endorsement by the Go programming language product.

*** Logo

The Go Gopher was originally created by Renee French and is licensed under the [[https://creativecommons.org/licenses/by/4.0/][Creative Commons 4.0 Attribution License]]. Consequently, the GoForge logo is also licensed under the [[https://creativecommons.org/licenses/by/4.0/][Creative Commons 4.0 Attribution License]], which allows you to use, share, and adapt the logo as long as you provide appropriate attribution. However, please note that the GoForge name and slogan are proprietary and owned by goforge.dev. Any use of the GoForge name and slogan must be in accordance with their terms and policies.

** Inspired by

- Mix: a build tool for Elixir that creates, compiles, tests, manages dependencies, and much more.
- Polylith: a framework for architecting composable projects in a variety of languages
- Leiningen: a project automation framework for Clojure
- Cobra: a Go framework for making CLI apps
- Viper: a Go library for configuration management
- Maven and Gradle: build automation and project management tools for Java

** Why use GoForge?

- Straightforward way to make composable code in Go.
- See what's going on in a project at a glance.
- Straightforward commands to make and extend a project.
- Straightforward commands to make and version artifacts.
- Plays nicely with Git & GitHub.
- Plays nicely with Cobra.
- Plays nicely with Viper.

** How to use GoForge?

#+BEGIN_SRC bash
goforge new project www.brain-fuel.co/goforge
#+END_SRC

#+BEGIN_SRC bash
goforge new project github.com/brain-fuel/goforge
#+END_SRC

#+BEGIN_SRC bash
goforge new project www.brain-fuel.co/path/to/coolapp
#+END_SRC

#+BEGIN_SRC bash
goforge new base <base name>
#+END_SRC

#+BEGIN_SRC bash
goforge new app <app name>
goforge new app --cobra <app name>
#+END_SRC

** Commands

*** Show

**** Components
***** All
***** For a particular app
***** For a particular base

**** Bases
***** All
***** For a particular app
***** Using a particular component

**** Apps
***** All
***** Using a particular base
***** Using a particular component

**** Deps
***** All
***** For a particular component
***** For a particular base
***** For a particular app

*** New

With each new entity, it should be added to Git.

**** Project
**** Component
**** Base
**** App

*** Build
**** App
**** All Apps

*** Clean
**** All
**** App

*** Test
**** Component
**** All Components
**** Base
**** All Bases
**** App
**** All Apps

*** Tag

*** Bump
**** Major
**** Minor
**** Patch

*** Release

Build, Test, Tag

**** Major
**** Minor
**** Patch

** TODO

- Make GoForge compatible with GitHub Actions
